CREATE TABLE `fs_photo_lab_orders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `lab` varchar(191) NOT NULL,
  `order_no` varchar(64) NOT NULL,
  `bag_no` varchar(64) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `price_vat` decimal(10,2) DEFAULT NULL,
  `currency` char(3) DEFAULT NULL,
  `ordered_at` datetime(6) NOT NULL,
  `returned_at` datetime(6) DEFAULT NULL,
  `invoice` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `fs_film_scans` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `archive_no` int(10) unsigned NOT NULL,
  `folder_name` varchar(191) NOT NULL,
  `film_stock` varchar(64) NOT NULL,
  `cartridge` varchar(16) NOT NULL,
  `expiration_date` date DEFAULT NULL,
  `exposure_index` smallint(5) unsigned NOT NULL,
  `exposure_correction` varchar(32) NOT NULL,
  `camera` varchar(128) NOT NULL,
  `lens` text NOT NULL,
  `filter` text NOT NULL,
  `development_process` varchar(32) NOT NULL,
  `push_pull` tinyint(4) NOT NULL DEFAULT 0,
  `lab` varchar(128) NOT NULL,
  `lab_order_id` int(10) unsigned DEFAULT NULL,
  `scanned_at` datetime(6) NOT NULL,
  `scan_format` varchar(32) NOT NULL,
  `scan_width` int(10) unsigned NOT NULL,
  `scan_height` int(10) unsigned NOT NULL,
  `archive_format` varchar(128) NOT NULL,
  `corrections` varchar(64) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `accession_no` (`archive_no`) USING BTREE,
  KEY `idx_scanned_at` (`scanned_at`),
  KEY `idx_lab` (`lab`),
  KEY `fk_fs_film_scans_lab_order` (`lab_order_id`),
  CONSTRAINT `fk_fs_film_scans_lab_order` FOREIGN KEY (`lab_order_id`) REFERENCES `fs_photo_lab_orders` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `fs_film_exposure_dates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `film_scan_id` int(10) unsigned NOT NULL,
  `exposure_date` date NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_scan_date` (`film_scan_id`,`exposure_date`),
  KEY `idx_exposure_date` (`exposure_date`),
  CONSTRAINT `fk_exposures_scan` FOREIGN KEY (`film_scan_id`) REFERENCES `fs_film_scans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `fs_film_photos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `scan_id` int(10) unsigned NOT NULL,
  `subdir` varchar(255) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `status` enum('internal','ok_private','ok_public') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'internal',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_scan_subdir_filename` (`scan_id`,`subdir`,`filename`),
  KEY `idx_scan_id` (`scan_id`),
  KEY `idx_subdir` (`subdir`),
  CONSTRAINT `fk_film_photos_scan` FOREIGN KEY (`scan_id`) REFERENCES `fs_film_scans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `fs_film_ua` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(45) NOT NULL,
  `x_real_ip` varchar(45) DEFAULT NULL,
  `x_forwarded_for` varchar(1024) DEFAULT NULL,
  `x_web_id` varchar(255) DEFAULT NULL,
  `x_geo_provider` varchar(100) DEFAULT NULL,
  `x_geo_continent_code` char(2) DEFAULT NULL,
  `x_geo_country_code` char(2) DEFAULT NULL,
  `user_agent` text NOT NULL,
  `browser_name` varchar(100) DEFAULT NULL,
  `browser_version` varchar(100) DEFAULT NULL,
  `os_name` varchar(100) DEFAULT NULL,
  `os_version` varchar(100) DEFAULT NULL,
  `platform_type` varchar(32) DEFAULT NULL,
  `device_vendor` varchar(100) DEFAULT NULL,
  `device_model` varchar(191) DEFAULT NULL,
  `architecture` varchar(32) DEFAULT NULL,
  `bitness` varchar(16) DEFAULT NULL,
  `is_mobile` tinyint(1) unsigned DEFAULT NULL,
  `ua_brands` text DEFAULT NULL,
  `request_uri` varchar(1024) NOT NULL,
  `requested_film_scan_id` int(10) unsigned DEFAULT NULL,
  `requested_img` varchar(64) DEFAULT NULL,
  `referer` varchar(1024) DEFAULT NULL,
  `gpu_info` text DEFAULT NULL,
  `fonts` text DEFAULT NULL,
  `screen_resolution` varchar(50) DEFAULT NULL,
  `screen_physical` varchar(50) DEFAULT NULL,
  `gps_coords` varchar(100) DEFAULT NULL,
  `color_depth` varchar(10) DEFAULT NULL,
  `timezone` varchar(100) DEFAULT NULL,
  `language` varchar(50) DEFAULT NULL,
  `platform` varchar(100) DEFAULT NULL,
  `plugins` text DEFAULT NULL,
  `mime_types` text DEFAULT NULL,
  `timestamp` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_fs_film_ua_created_at` (`timestamp`) USING BTREE,
  KEY `idx_fs_film_ua_requested_film_scan_id` (`requested_film_scan_id`) USING BTREE,
  KEY `idx_fs_film_ua_requested_img` (`requested_img`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `fs_flickr_photosets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `photoset_id` varchar(32) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `owner_name` varchar(255) NOT NULL,
  `primary_photo` varchar(512) NOT NULL,
  `primary_photo_id` varchar(32) NOT NULL,
  `secret` varchar(32) NOT NULL,
  `server` varchar(32) NOT NULL,
  `farm` int(11) NOT NULL,
  `url` varchar(512) NOT NULL,
  `photoset_small_url` varchar(512) NOT NULL,
  `photoset_square_thumbnail_url` varchar(512) NOT NULL,
  `photoset_thumbnail_url` varchar(512) NOT NULL,
  `comment_count` int(11) NOT NULL,
  `number_of_photos` int(11) NOT NULL,
  `number_of_videos` int(11) NOT NULL,
  `total` int(11) NOT NULL,
  `view_count` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `date_updated` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_photoset` (`photoset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `fs_photo_equip` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `equip_type` enum('camera','lens','filter','case','bag','tripod','level','hood') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `equip_name` varchar(191) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `acquired_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `retired_at` datetime(6) DEFAULT NULL,
  `disposition_note` varchar(768) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `acquired_at` (`acquired_at`),
  KEY `retired_at` (`retired_at`),
  CONSTRAINT `chk_retire_time` CHECK (`retired_at` is null or `retired_at` >= `acquired_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `fs_photo_tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `equip_id` int(10) unsigned NOT NULL,
  `flickr_tags` varchar(191) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `fk_equip` (`equip_id`),
  CONSTRAINT `fk_equip` FOREIGN KEY (`equip_id`) REFERENCES `fs_photo_equip` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;
